server:
  port: 18080

netty:
  port: 18081
  debug: true
  handler:
    protocol: websocket # tcp/websocket
    serial_algo: json # 0: protobuf；1: json

spring:
  application:
    name: t-chat-server
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /doc.html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.56.9.126:3306/t_chat?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT
    username: root
    password: WfNYnraEOynLn87e
  redis:
    host: 123.56.9.126
    port: 6379
    password: gNVA3tluQAkuKVWn
    database: 0
    timeout: 1000ms

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑为删除值（默认为 0）
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mappers/**.xml

auth:
  expire-times: # 单位：min
    access-token: 120 # 2hour
    refresh-token: 10080 # 7day